app_login:
  path: /
  defaults: {_controller: App\Controller\LoginController::index}

app_register:
  path: /register
  defaults: {_controller: App\Controller\RegistrationController::register}

app_logout:
  path: /logout
  defaults: {_controller: App\Controller\LogoutController::index}

app_inicio:
  path: /inicio/{pantalla}
  defaults: {_controller: App\Controller\InicioController::index, pantalla: '0'}

app_dashboard:
  path: /dashboard
  defaults: {_controller: App\Controller\InicioController::dashboard}

app_pisos:
  path: /locacion/pisos
  defaults: {_controller: App\Controller\LocacionController::pisos}

app_nuevoPiso:
  path: /locacion/nuevoPiso
  defaults: {_controller: App\Controller\LocacionController::nuevoPiso}

app_eliminarPiso:
  path: /locacion/eliminarPiso/{id}
  defaults: {_controller: App\Controller\LocacionController::eliminarPiso}

app_habitaciones:
  path: /locacion/habitaciones
  defaults: {_controller: App\Controller\LocacionController::habitaciones}

app_nuevaHabitacion:
  path: /locacion/nuevaHabitacion
  defaults: {_controller: App\Controller\LocacionController::nuevaHabitacion}

app_eliminarHabitacion:
  path: /locacion/eliminarHabitacion/{id}
  defaults: {_controller: App\Controller\LocacionController::eliminarHabitacion}

app_tipodoc:
  path: /configuracion/tipodoc
  defaults: {_controller: App\Controller\ConfiguracionController::tipoDoc}

app_guardarTipodoc:
  path: /configuracion/guardarTipodoc
  defaults: {_controller: App\Controller\ConfiguracionController::guardarTipodoc}

app_eliminarTipodoc:
  path: /configuracion/eliminarTipodoc/{id}
  defaults: {_controller: App\Controller\ConfiguracionController::eliminarTipodoc}

app_companias:
  path: /configuracion/companias
  defaults: {_controller: App\Controller\ConfiguracionController::companias}

app_nuevaCompania:
  path: /configuracion/nuevaCompania
  defaults: {_controller: App\Controller\ConfiguracionController::nuevaCompania}

app_eliminarCompania:
  path: /configuracion/eliminarCompania/{id}
  defaults: {_controller: App\Controller\ConfiguracionController::eliminarCompania}

app_clientes:
  path: /clientes
  defaults: {_controller: App\Controller\ClientesController::lista}

app_guardarClientes:
  path: /clientes/guardarClientes
  defaults: {_controller: App\Controller\ClientesController::guardarClientes}

app_eliminarClientes:
  path: /clientes/eliminarClientes/{id}
  defaults: {_controller: App\Controller\ClientesController::eliminarClientes}

app_obtenerClientexCedula:
  path: /clientes/eliminarClientes/{cedula}
  defaults: {_controller: App\Controller\ClientesController::obtenerClientexCedula}

app_reservas:
  path: /reservas
  defaults: {_controller: App\Controller\ReservasController::lista}

app_nuevaReserva:
  path: /nuevaReserva
  defaults: {_controller: App\Controller\ReservasController::nuevaReserva}

app_crearCheckin:
  path: /crearCheckin/{id}
  defaults: {_controller: App\Controller\ReservasController::crearCheckin}

app_guardarReserva:
  path: /guardarReserva
  defaults: {_controller: App\Controller\ReservasController::guardarReserva}

app_eliminarReserva:
  path: /eliminarReserva/{id}
  defaults: {_controller: App\Controller\ReservasController::eliminarReserva}

app_obtenerDatosClienteReserva:
  path: /obtenerDatosClienteReserva/{id}
  defaults: {_controller: App\Controller\ReservasController::obtenerDatosClienteReserva}

app_abrirTurno:
  path: /abrirTurno
  defaults: {_controller: App\Controller\TurnosController::abrirTurno}

app_servicios:
  path: /servicios
  defaults: {_controller: App\Controller\ConfiguracionController::servicios}

app_tiposServ:
  path: /tiposServicios
  defaults: {_controller: App\Controller\ConfiguracionController::tiposServicios}

app_guardarTiposServ:
  path: /guardarTiposServ
  defaults: {_controller: App\Controller\ConfiguracionController::guardarTiposServ}

app_eliminarTiposServ:
  path: /eliminarTiposServ/{id}
  defaults: {_controller: App\Controller\ConfiguracionController::eliminarTiposServ}

app_listaServ:
  path: /listaServicios/{filtro}
  defaults: {_controller: App\Controller\ConfiguracionController::listaServicios, filtro: '0'}

app_guardarServicio:
  path: /guardarServicio
  defaults: {_controller: App\Controller\ConfiguracionController::guardarServicio}

app_cambiaEstadoServicio:
  path: /cambiaEstadoServicio/{id},{estado}
  defaults: {_controller: App\Controller\ConfiguracionController::cambiaEstadoServicio}

app_eliminarServicio:
  path: /eliminarServicio/{id}
  defaults: {_controller: App\Controller\ConfiguracionController::eliminarServicio}

app_obtenerServicio:
  path: /obtenerServicio/{id}
  defaults: {_controller: App\Controller\ConfiguracionController::obtenerServicio}

app_stock:
  path: /stock
  defaults: {_controller: App\Controller\StockController::listas}

app_productos:
  path: /productos
  defaults: {_controller: App\Controller\StockController::productos}

app_guardarProducto:
  path: /guardarProducto
  defaults: {_controller: App\Controller\StockController::guardarProducto}

app_inventario:
  path: /inventario
  defaults: {_controller: App\Controller\StockController::inventario}

app_entradas:
  path: /entradas
  defaults: {_controller: App\Controller\StockController::entradas}

app_guardarEntrada:
  path: /guardarEntrada
  defaults: {_controller: App\Controller\StockController::guardarEntrada}

app_cargarProductosPlano:
  path: /cargarProductosPlano
  defaults: {_controller: App\Controller\StockController::cargarProductosPlano}

app_obtenerProducto:
  path: /obtenerProducto/{id}
  defaults: {_controller: App\Controller\StockController::obtenerProducto}

app_updateCantProducto:
  path: /updateCantProducto/{id},{accion},{cantidad}
  defaults: {_controller: App\Controller\StockController::updateCantProducto}






